# Sitewide configuration settings. Set `title` to the site title, which
# will be appended to the URL following {{page.title}} |

title: Think Open Solutions Brasil
auto: true
server: true
url: http://localhost:4000
baseurl: 
permalink: /:categories/:title
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - ga-api-privatekey.p12
  - Gemfile
  - Gemfile.lock
languages: &languages
  - name: 'Portugu&ecirc;s'
    value: 'pt-br'
  #- name: 'English'
  #  value: 'en'
  #- name: 'Espa&ntilde;ol'
  #  value: 'es'
siteurl: 'http://www.thinkopensolutions.com.br'
searchurl: 'http://search.thinkopensolutions.com.br'
searchproxy: 'http://www.thinkopensolutions.com.br'
   
# Custom Collections
# Creates a globally accessible list of posts based on these specified metadata variables
jekyll_collect:
  - topics
  
# Settings for Google Analytics post sorting
jekyll_ga:
  host: 'insert_host'
  port: 'insert_port'
  service_account_email: 527118645338@developer.gserviceaccount.com
  key_file: ga-api-privatekey.p12
  key_secret: notasecret
  profileID: ga:78051758
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric

# Advanced list sorting
jekyll_sort:
  - src: posts
    by: date
    direction: down
    dest: blogposts
    include_categories:
    - blog
  - src: posts
    by: title
    direction: up
    dest: glossary
    include_categories:
    - glossary

# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  siteurl: "http://www.thinkopensolutions.com.br"
  relativeLinks: "http://www.thinkopensolutions.com.br/resources/prose/relativeLinks.jsonp"
  site:
    tags: "http://www.thinkopensolutions.com.br/api/tags.jsonp"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "meta-description"
        field:
          element: "text"
          label: "Meta Description" 
          value: ""
      - name: "title-short"
        field:
          element: "text"
          label: "Title Short"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "blog"
              value: "blog"
          selected: "blog"
      - name: "comments"
        field:
          element: "select"
          label: "Enable comments"
          placeholder: "Default"
          options:
            - name: "yes"
              value: "yes"
            - name: "no"
              value: "no"
          selected: "yes"