title: Think Open Solutions Brasil
siteurl: 'http://www.thinkopensolutions.com.br'
lang: pt-br

safe:        true
auto:        true
server:      false
server_port: 4000
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
#permalink:   pretty
permalink: /:categories/:title

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# Advanced list sorting
jekyll_sort:
  - src: posts
    by: date
    direction: down
    dest: blogposts
    include_categories:
    - blog

# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  siteurl: "http://www.thinkopensolutions.com.br/"
  relativeLinks: "http://www.thinkopensolutions.gov/resources/prose/relativeLinks.jsonp"
  site:
    tags: "http://www.thinkopensolutions.com.br/api/tags.jsonp"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "meta-description"
        field:
          element: "text"
          label: "Meta Description" 
          value: ""
      - name: "title-short"
        field:
          element: "text"
          label: "Title Short"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "blog"
              value: "blog"
          selected: "blog"
      - name: "comments"
        field:
          element: "select"
          label: "Enable comments"
          placeholder: "Default"
          options:
            - name: "yes"
              value: "yes"
            - name: "no"
              value: "no"
          selected: "yes"